export function demoProject() {
  return {
    version: 1,
    name: "Прототип к демодню",
    deadline: 7,
    people: [
      { id: "mira", name: "Мира", capacity: 6, away: [] },
      { id: "dan", name: "Дан", capacity: 6, away: [] },
      { id: "sam", name: "Сэм", capacity: 4, away: [] },
    ],
    tasks: [
      {
        id: "idea",
        title: "Сценарий продукта",
        personId: "mira",
        hours: 6,
        dependencies: [],
        required: true,
        releaseDay: 1,
      },
      {
        id: "design",
        title: "Экраны и навигация",
        personId: "mira",
        hours: 12,
        dependencies: ["idea"],
        required: true,
        releaseDay: 1,
      },
      {
        id: "engine",
        title: "Расчётный модуль",
        personId: "dan",
        hours: 18,
        dependencies: ["idea"],
        required: true,
        releaseDay: 1,
      },
      {
        id: "ui",
        title: "Сборка интерфейса",
        personId: "dan",
        hours: 12,
        dependencies: ["design"],
        required: true,
        releaseDay: 1,
      },
      {
        id: "test",
        title: "Проверка сценариев",
        personId: "sam",
        hours: 8,
        dependencies: ["engine", "ui"],
        required: true,
        releaseDay: 1,
      },
      {
        id: "pitch",
        title: "Подготовка презентации",
        personId: "mira",
        hours: 6,
        dependencies: ["design"],
        required: true,
        releaseDay: 1,
      },
      {
        id: "analytics",
        title: "Дополнительная аналитика",
        personId: "dan",
        hours: 6,
        dependencies: ["engine"],
        required: false,
        releaseDay: 1,
      },
      {
        id: "polish",
        title: "Анимации переходов",
        personId: "mira",
        hours: 6,
        dependencies: ["design"],
        required: false,
        releaseDay: 1,
      },
    ],
  };
}
